
[window]
opacity = 0.75

[font]
normal = { family = "AnonymiceProNerdFontMono", style = "Regular" }

size = 15.5

[colors]
vi_mode_cursor = {text = '#000000', cursor = '#ffa0a0'}

[keyboard]
bindings = [
    { key = "j", mods = "Control | Shift", chars = "♠" }, # unicode for ♠: "\u2660"
    { key = "k", mods = "Control | Shift", chars = "♡" }
]

[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin_latte.toml"
]
