add_newline = false

format = """
$directory\
$git_branch\
$git_metrics\
$git_status\
$fill\
$conda\
$python\
$kubernetes\
$time
"""

[conda]
ignore_base = false
symbol = '󰊰'
format = ' [$symbol $environment]($style) '


[fill]
symbol = ' '


[git_status]
style = '#ffffff bg:cyan'
format = '([](fg:cyan)[ $all_status$ahead_behind ]($style)[](fg:cyan))'


[git_branch]
truncation_length = 25
style = '#ffffff bg:cyan'
format = '[](bold fg:cyan)[$symbol$branch(:$remote_branch)]($style)[](fg:cyan)'


[git_metrics]
disabled = false
added_style = 'bold green bg:black'
deleted_style = 'bold red bg:black'
format = '([](fg:black)[+$added ]($added_style))([-$deleted]($deleted_style)[](fg:black))'


[time]
disabled = false
style = 'bold black bg:yellow'
format = '[](yellow)[ $time ]($style)'
#format = '[](yellow)[ $time ]($style)'


[directory]
style = 'fg:#ffffff bg:black'
format = '[ $path ]($style)[$read_only]($read_only_style)[](fg:black)'


[python]
symbol = ' '
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
#pyenv_version_name = true


[kubernetes]
format = '[](fg:$style)[ $symbol $context ](bg:$style fg:#000000)[](fg:$style bg:white)[$namespace](bg:white fg:#000000)[](fg:white bg:$style)[](fg:$style)'
disabled = false
style = "white"


[[kubernetes.contexts]]
context_pattern = "minikube"
style = "green"

[[kubernetes.contexts]]
context_pattern = ".*ssa-dev"
style = "blue"
context_alias = "ssa-dev"

[[kubernetes.contexts]]
context_pattern = ".*ssa-prod"
style = "red"
context_alias = "ssa-prod"

