add_newline = false

format = """
$directory\
$git_branch\
$git_metrics\
$git_status\
$fill\
$conda\
$python\
$kubernetes\
$time
"""


[fill]
# style = 'bg:#313244'
symbol = ' '

[directory]
style = 'fg:#1e1e2e bg:bright-blue'
format = '[ $path ]($style)[$read_only]($read_only_style)[](fg:bright-blue)'

[git_branch]
truncation_length = 25
style = 'bold fg:#1e1e2e bg:bright-cyan'
format = '[](bold fg:bright-cyan)[ $symbol$branch (:$remote_branch)]($style)[](fg:bright-cyan)'

[git_metrics]
disabled = false
added_style = 'bold fg:#1e1e2e bg:green'
deleted_style = 'bold fg:#EFF1F5 bg:red'
format = '([](fg:green)[+$added]($added_style)[](fg:red bg:green))([-$deleted]($deleted_style)[](fg:red))'

[git_status]
style = 'fg:#1e1e2e bg:yellow'
format = '([](fg:yellow)[ $all_status$ahead_behind ]($style)[](fg:yellow))'

[time]
disabled = false
style = 'bold #1e1e2e bg:#b4befe'
format = '[](#b4befe)[ $time ]($style)'
#format = '[](yellow)[ $time ]($style)'

[conda]
ignore_base = false
symbol = '󰊰'
format = ' [$symbol $environment]($style) '

[python]
symbol = ' '
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
#pyenv_version_name = true

[kubernetes]
format = '[](fg:$style)[ $symbol $context ](bg:$style fg:#000000)[](fg:$style bg:white)[$namespace](bg:white fg:#000000)[](fg:white bg:$style)[](fg:$style)'
disabled = false
style = "white"

[[kubernetes.contexts]]
context_pattern = "minikube"
style = "green"

[[kubernetes.contexts]]
context_pattern = ".*ssa-dev"
style = "blue"
context_alias = "ssa-dev"

[[kubernetes.contexts]]
context_pattern = ".*ssa-prod"
style = "red"
context_alias = "ssa-prod"

